### ISSUE TITLE
Current version of the package depends on a beta dart SDK

### ISSUE THREAD

**Issue by pradt** [Nolence/async_button_builder#11]
I've used the latest version of this package and noticed that it requires a minimum dart sdk of 2.12.0 and the current stable version (listed on https://dart.dev/get-dart) is 2.10. 

Can this be used to only rely on stable versions of dart sdk ?

**Comment by Nolence** [comment]
Hi !

Yeah, I've been meaning to create a stable version alongside the nnbd version but forgot. Will get that out very soon

**Comment by Nolence** [comment]
I published a stable version that should correspond with the stable version of flutter.

See version 2.0.7. Let me know if that doesn't do it
